# Generated by Django 4.2 on 2023-04-16 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('FREE', 'FREE'), ('PLAN', 'PLAN'), ('CANCELED', 'CANCELED'), ('IN_ROAD', 'IN_ROAD'), ('DONE', 'DONE')], default='FREE', max_length=255)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('free_volume', models.PositiveSmallIntegerField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('number_and_region', models.CharField(max_length=9, unique=True)),
                ('max_load_capacity', models.PositiveSmallIntegerField()),
                ('max_loading_volume', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('WAIT', 'WAIT'), ('IN_TRANSIT', 'IN_TRANSIT'), ('RETURN', 'RETURN')], max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
        migrations.AddConstraint(
            model_name='transport',
            constraint=models.CheckConstraint(check=models.Q(('max_load_capacity__range', (1, 40))), name='max_load_capacity_constraint'),
        ),
        migrations.AddConstraint(
            model_name='transport',
            constraint=models.CheckConstraint(check=models.Q(('max_loading_volume__range', (5, 150))), name='max_loading_volume_constraint'),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.product'),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.stock'),
        ),
        migrations.AddField(
            model_name='stock',
            name='products',
            field=models.ManyToManyField(through='transportation.StockProduct', to='transportation.product'),
        ),
        migrations.AlterUniqueTogether(
            name='stockproduct',
            unique_together={('product', 'stock')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('city', 'address')},
        ),
    ]
