# Generated by Django 4.2 on 2023-06-04 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, verbose_name='Город отправки')),
                ('destination', models.CharField(max_length=255, verbose_name='Город доставки')),
                ('status', models.CharField(blank=True, choices=[('FREE', 'FREE'), ('PLAN', 'PLAN'), ('CANCELED', 'CANCELED'), ('IN_ROAD', 'IN_ROAD'), ('DONE', 'DONE')], default='FREE', max_length=255, verbose_name='Статус')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выручка')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('free_volume', models.PositiveSmallIntegerField(verbose_name='свободный объем')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Склад и товары',
                'verbose_name_plural': 'Склады и товары',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('number_and_region', models.CharField(max_length=9, unique=True, verbose_name='Номер и регион')),
                ('max_load_capacity', models.PositiveSmallIntegerField(verbose_name='Максимальный вес')),
                ('max_loading_volume', models.PositiveSmallIntegerField(verbose_name='Максимальный объем')),
                ('status', models.CharField(choices=[('WAIT', 'Ожидает'), ('IN_TRANSIT', 'В пути'), ('RETURN', 'Возвращается')], max_length=255, verbose_name='Статус')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
        migrations.AddConstraint(
            model_name='transport',
            constraint=models.CheckConstraint(check=models.Q(('max_load_capacity__range', (1, 40))), name='max_load_capacity_constraint'),
        ),
        migrations.AddConstraint(
            model_name='transport',
            constraint=models.CheckConstraint(check=models.Q(('max_loading_volume__range', (5, 150))), name='max_loading_volume_constraint'),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.product'),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.stock'),
        ),
        migrations.AddField(
            model_name='stock',
            name='products',
            field=models.ManyToManyField(through='transportation.StockProduct', to='transportation.product'),
        ),
        migrations.AlterUniqueTogether(
            name='stockproduct',
            unique_together={('product', 'stock')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('city', 'address')},
        ),
    ]
